# Generated by Django 5.2.7 on 2025-10-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bday', models.DateField()),
                ('address', models.TextField()),
                ('contact_num', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('program_and_yr', models.CharField(max_length=100)),
                ('scholarship', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=50)),
            ],
        ),
    ]
