# Generated by Django 5.2.8 on 2026-01-20 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_applicationdocument'),
        ('home', '0004_program_program_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='home.application'),
        ),
    ]
