# Generated by Django 5.2.8 on 2026-01-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_applicationdocument_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_remarks_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='popup',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_popups', to='accounts.student'),
        ),
    ]
