# Generated by Django 6.0.2 on 2026-02-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='barangay',
            field=models.CharField(blank=True, choices=[('Aningway-Sacatihan', 'Aningway-Sacatihan'), ('Asinan (Poblacion)', 'Asinan (Poblacion)'), ('Asinan Proper', 'Asinan Proper'), ('Baraca-Camachile (Poblacion)', 'Baraca-Camachile (Poblacion)'), ('Batiawan', 'Batiawan'), ('Calapacuan', 'Calapacuan'), ('Calapandayan (Poblacion)', 'Calapandayan (Poblacion)'), ('Cawag', 'Cawag'), ('Ilwas (Poblacion)', 'Ilwas (Poblacion)'), ('Mangan-Vaca', 'Mangan-Vaca'), ('Matain', 'Matain'), ('Naugsol', 'Naugsol'), ('Pamatawan', 'Pamatawan'), ('San Isidro', 'San Isidro'), ('Santo Tomas', 'Santo Tomas'), ('Wawandue (Poblacion)', 'Wawandue (Poblacion)')], max_length=50, null=True),
        ),
    ]
