# Generated by Django 6.0.2 on 2026-02-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_student_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(blank=True, choices=[('Junior High School', 'Junior High School'), ('Senior High School', 'Senior High School'), ('Undergraduate', 'Undergraduate'), ("Master's", "Master's"), ('Doctoral', 'Doctoral'), ('Board Exam', 'Board Exam')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='program_and_yr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
