# Generated by Django 5.2.8 on 2026-02-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_admin_full_name_adminlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
