# Generated by Django 5.2.8 on 2026-02-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_student_achievements_student_college_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='warning_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
