# Generated by Django 5.2.8 on 2026-03-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_student_approved_at_student_warning_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
