# Generated by Django 5.2.7 on 2025-10-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_student_id_student_student_id_application'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_applications', to='accounts.student'),
        ),
    ]
