# Generated by Django 5.2.8 on 2026-01-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_application_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='application_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='application_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
