# Generated by Django 5.2.8 on 2026-01-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_program_application_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_image',
            field=models.ImageField(blank=True, null=True, upload_to='program_images/'),
        ),
    ]
