# Generated by Django 5.2.8 on 2026-01-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_program_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_remarks_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
