# Generated by Django 5.2.8 on 2026-01-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_application_is_remarks_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('Financial Assistance', 'Financial Assistance'), ('Scholarship', 'Scholarship'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
