# Generated by Django 5.2.8 on 2026-02-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_program_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='document_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
