# Generated by Django 5.2.8 on 2026-03-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='target_student_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
