# Generated by Django 5.2.8 on 2026-03-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_program_target_student_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='max_slots',
            field=models.IntegerField(default=0, help_text='Maximum number of applications allowed. 0 for unlimited.'),
        ),
    ]
