# Generated by Django 5.2.8 on 2026-03-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_program_max_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_paid_out',
            field=models.BooleanField(default=False),
        ),
    ]
